kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
  commands:
  - pip install --no-dependencies nuscenes-devkit opencv-python-headless scikit-learn joblib pyquaternion cachetools
  - pip install -r requirements.txt
  - apt-get update && apt-get -y install libglib2.0-0  # needed by opencv
  - flake8 --config=.flake8 .
  - python setup.py develop
  - . ./setenv.sh
  - pytest --cov=kaolin/ tests/
