kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
  commands:
  - pip install --upgrade pip>=18.0.0
  - pip install flake8==3.7.9 \
                flake8-bugbear==20.1.4 \
                flake8-comprehensions==3.2.2 \
                flake8-mypy==17.8.0 \
                flake8-pyi==19.3.0 \
                pytest==5.4.2 \
                pycov==2.8.1
  - pip install --no-dependencies -r requirements.txt
  - apt-get update && apt-get -y install libglib2.0-0  # needed by opencv
  - flake8 --config=.flake8 .
  - python setup.py develop
  - . ./setenv.sh
  - pytest --cov=kaolin/ tests/
