kind: pipeline
type: docker
name: default

environment:
  CUDA_VERSION: "10.1"
  PYTORCH_VERSION: "1.6"
  CUDNN_VERSION: "7"
  TORCH_CUDA_ARCH_LIST: "5.2 6.0 6.1 7.0 7.5+PTX"
  KAOLIN_INSTALL_EXPERIMENTAL: "1"

steps:
- name: submodules
  image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  commands:
  - apt-get update && apt-get install -y git
  - git submodule update --init --recursive

- name: flake8
  image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  commands:
  - >
    apt-get update && apt-get install -y --no-install-recommends
    python3-pip
  - pip3 install --upgrade pip>=19.3
  - pip install -r tools/ci_requirements.txt
  - flake8 --config=.flake8 .

- name: pytest
  image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  commands:
  - >
    apt-get update && apt-get install -y --no-install-recommends
    build-essential
    curl
    && apt-get clean
    && rm -rf /var/lib/apt/lists/*
  - >
    curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&
    sh ~/miniconda.sh -b -p /opt/conda &&
    /opt/conda/bin/conda install -y python=3.7 &&
    /opt/conda/bin/conda clean -ya
  - export PATH=/opt/conda/bin:$PATH
  - pip install --upgrade pip>=19.3
  - conda install -y pytorch==1.6 cudatoolkit=10.1 -c pytorch
  - conda install -c conda-forge nodejs
  - >
    apt-get update && apt-get install -y --no-install-recommends
    libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  - npm install
  - python setup.py develop
  - pip install -r tools/ci_requirements.txt
  - pytest --cov=kaolin/ tests/python tests/integration && pytest --doctest-modules kaolin/
