kind: pipeline
type: docker
name: default

environment:
  CUDA_VERSION: "10.1"
  PYTORCH_VERSION: "1.6"
  CUDNN_VERSION: "7"
  TORCH_CUDA_ARCH_LIST: "5.2 6.0 6.1 7.0 7.5+PTX"

steps:
- name: flake8
  image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  commands:
  - >
    apt-get update && apt-get install -y --no-install-recommends
    ca-certificates
    python3-pip
  - pip3 install --upgrade pip>=19.3
  - pip install -r tools/ci_requirements.txt
  - flake8 --config=.flake8 .

- name: pytest
  image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
  commands:
  - >
    apt-get update && apt-get install -y --no-install-recommends
    build-essential
    curl
    git
    libglib2.0-0
    && apt-get clean
    && rm -rf /var/lib/apt/lists/*
  - >
    curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&
    sh ~/miniconda.sh -b -p /opt/conda &&
    /opt/conda/bin/conda install -y python=${PYTHON_VERSION} &&
    /opt/conda/bin/conda clean -ya
  - pip install --upgrade pip>=19.3
  - export PATH=/opt/conda/bin:$PATH
  - conda install -y pytorch==${PYTORCH_VERSION} cudatoolkit=${CUDA_VERSION} -c pytorch
  - python setup.py develop
  - pip install -r tools/ci_requirements.txt
  - pytest --cov=kaolin/ tests/python && pytest --doctest-modules kaolin/
