version: 2

python:
   version: 3.7
   system_packages: true
   install:
      - requirements: docs/readthedocs_requirements.txt
      - requirements: tools/doc_requirements.txt
      - method: setuptools
        path: '.'

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true
