version: 2

python:
 install:
  - requirements: docs/readthedocs_requirements.txt
  - requirements: tools/doc_requirements.txt
  - method: setuptools
    path: '.'

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

sphinx:
 configuration: docs/conf.py
 fail_on_warning: true
